nameinput = input("Enter your full name: ").title()
print ("Name: ")
print (nameinput)
ageinput = int(input("Enter your age: "))
print ("Age: ")
print (ageinput)
addressinput = input("Enter your address: ").title()
print ("Address: ")
print (addressinput)
